// Section component exports for the landing page
export { Hero } from './hero/Hero'
export { HeroTitle } from './hero/HeroTitle'
export { HeroEntrance } from './hero/HeroEntrance'
export { BreathIndicator } from './hero/BreathIndicator'
export { PositioningLine } from './hero/PositioningLine'
export { Philosophy } from './philosophy/Philosophy'
export { Services } from './Services'
export { ServiceTags } from './ServiceTags'
export { Projects } from './projects'
export { Testimonial } from './Testimonial'
export { Contact } from './Contact'
